[project]
name = "adventofcode2024"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.3",
    "pillow>=11.0.0",
    "pytest>=8.3.4",
    "ruff>=0.8.1",
]


[tool.ruff]
line-length = 120
